### ISSUE TITLE
Cannot set property 'smokesignals' of undefined

### ISSUE THREAD

**Issue by jaumard** [trailsjs/trailpack#31]
#### Issue Description

With last version of Trailpack and smoke signals I have this error : 

```
TypeError: Cannot set property 'smokesignals' of undefined
    at SmokesignalsTrailpack.Trailpack (/Users/jaumard/IdeaProjects/trailpack-annotations/node_modules/trailpack/index.js:51:31)
    at SmokesignalsTrailpack (/Users/jaumard/IdeaProjects/trailpack-annotations/node_modules/smokesignals/lib/trailpack.js:7:10)
    at /Users/jaumard/IdeaProjects/trailpack-annotations/node_modules/trails/index.js:64:59
    at Array.map (native)
```
#### Environment
- node version: all
- trails version: all
- operating system: all

**Comment by jaumard** [comment]
Each Trailpack need to be updated in order to work with last version of Trails, here is some PR about this : 

a lot of trailpack cannot be update before this one https://github.com/trailsjs/smokesignals/pull/11

https://github.com/trailsjs/trailpack-core/pull/52
https://github.com/trailsjs/trailpack-bootstrap/pull/3
https://github.com/trailsjs/trailpack-repl/pull/34

**Comment by jaumard** [comment]
No more problem
